### PR TITLE
Full support for esm and 7.0

### PR DESCRIPTION
**Pull request by farfromrefug**
Could you release it under rc-esm tag?

Thanks

### CODE REVIEW

**Comment by halfnelson** [comment]
I have made some changes to this at https://github.com/halfnelson/svelte-native/tree/esm_7.0
but it currently won't pass the unit tests
 `cd demo, npm install, tns test android` gives 
```
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.demo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Building UI from XML. @bundle-app-root.xml:1:1
System.err:  > Class constructor Observable cannot be invoked without 'new'
```
happy to take PRs against this branch to get it working

**Comment by farfromrefug** [comment]
That s weird. But i also thought about something. The mjs build should dropped and the js version should be full es2017 just like the core.
About your error in will try

**Comment by farfromrefug** [comment]
@halfnelson i updated the branch to support tests 
However it requires an updated `nativescript-ui-test-runner`. The PR is here https://github.com/NativeScript/nativescript-unit-test-runner/pull/43

Any chance you could still publish an rc or rc-esm?

**Comment by halfnelson** [comment]
the esm_7.0 branch of this repo has the changes, and I have deployed an `rc-esm` dist tagged npm package. Thanks for the effort :),

**Pull request closed without merging**
