### PR TITLE
feat: allow overriding a registered element

### PR DESCRIPTION
**Pull request by farfromrefug**
Added an options parameter to registerElement

### CODE REVIEW

**Comment by halfnelson** [comment]
Thanks for the PR. Is it possible to get this as a change on master that only includes the option to override a method. This PR includes the removal of normalized attribute names (which will break things!) and the logging changes discussed elsewhere. Happy to merge a PR with just the options field (and update to the docs in site if possible :))

**Comment by farfromrefug** [comment]
My bad it was a test (fail) on my side will recreate a PR

**Comment by halfnelson** [comment]
Going to close this so a new PR can be made with just the changes required. But there are a few things in here that I should probably apply to svelte-native, such as the setText double call, and the deprecated methods

**Comment by farfromrefug** [comment]
@halfnelson sorry yes actually it was a PR on my master :s 
Will try and create many PRs today!

**Pull request closed without merging**
